### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by olavim** [EssKayz/CertificateManager#2]
Projekti ladattu 13.10. klo 22:00.

### Yleistä

Dokumentaatio on mielestäni onnistunutta, ja sovelluksen käyttö sujui hyvin sen luettuani. Kooditasolla sovelluksen rakenne on suurimmaksi osaksi järkevää (pieni huomio tästä alempana) ja sen seuraaminen on helppoa.

Lomakkeiden validointi on myös hyvällä mallilla, ja olemassaolevan käyttäjän tarkistus rekisteröityessä löytyy myös. Tästä kuitenkin pieni huomio alempana. Sovellus ei myöskään räjähtänyt, vaikka syötin kaikenlaista moskaa kaikkiin kenttiin mitä löysin.

Hyvää työtä myös ulkoasun kannalta!

### Huomioita

- Rekisteröitymissivulla lukee
  > By clicking Register, you agree to the Terms and Conditions

  Mutta kuitenkin sen vieressä on toggle-nappi jota painamatta en voi rekisteröityä 😉 

- Equipmenttiin liittyvät asiat voisi olla omassa moduulissaan. Tällä hetkellä equipment-rajapinta on päätason viewssa (`/auth/addEq`, `/auth/removeEq`), form löytyy auth-moduulista, ja model löytyy products-moduulista. Tätä lukuunottamatta asiat olivat loogisissa paikoissa.

- Mikään POST-rajapinta ei ole turvattu CSRF-hyökkäyksiltä. Luultavasti helpottanut testaamista alussa, mutta tässä vaiheessa uskon, että tätä kannattaisi jo alkaa miettimään. Käytännössähän formeista pitää vain poistaa `csrf = false` flagi, ja lisätä csrf-token jokaiseen formiin templateissa.

  Tällä hetkellä jos käyttäjä on kirjautunut sisään sovellukseesi (vaikkapa herokussa), hyökkääjä voi huijata käyttäjän sivulle missä on allaoleva html-pätkä
  ```
  <form action="https://eqmanager.herokuapp.com/auth/addEq" method="post">
	  <input type="hidden" name="model" value="1">
	  <input type="hidden" name="serialnumber" value="1234">
	  <input type="submit">
  </form>
  ```
  ja kun käyttäjä painaa nappia, lisätään tämän equipment-listalle sarjanumero 1234 mallilla APEX M750.

- Käyttäjä voi rekisteröityä tunnuksella ja/tai nimellä, joka koostuu pelkistä välilyönneistä. Käyttäjän tiedot eivät toisaalta taida näkyä muille, joten tämä ei ole kovin vaarallista.

- Pelkistä välilyönneistä koostuva nimi kelpaa luodessa uutta manufactureria, modelia, tai classificationia.

- Jokaisen classificationin kuvauksen alussa on välilyönti. Siis esim. `IP68` kuvaus on renderöity: 
" Waterproof".

- Voin equipment-listassa avata developer toolsin ja muuttaa vaikkapa delete-formin actionia osoittamaan johonkin muuhun equpmenttiin. Testikäyttäjälläni (olavim) on equipmentit ID:illä `5` ja `6`. Muutin toisen delete-formin pointtaamaan ID:seen `3`, ja painoin delete-nappia. Ilmeisesti jonkun muun käyttäjän equipment katosi taivaan tuuliin, sillä omastani ei mitään kadonnut, ja models-listassa näkyvä APEX M800 mallin broken-prosentti muuttui...

  Eli tässä suosittelisin laittamaan tarkistuksen, että poistettava/muokattava equipment tosiaan on poistajan/muokkaajan omistama.

- Käytettävyyden kannalta olisi mukavaa, jos lisäämisen/muokkaamisen/poistamisen jälkeen pääsisin aina uuteen tai _edelliseen_ näkymään. Esimerkiksi jos lisään classificationille uuden tuotteen, niin tämän jälkeen haluaisin muokatun classificationin avautuvan automaattisesti.

- `SECRET_KEY` konffi olisi ehkä hyvä lukea environmentista, ja käyttää `urandom(32)` vain jos sitä ei ole asetettu. Tällä hetkellä aina kun sovellus päivittyy, niin `SECRET_KEY` muuttuu, joka johtaa kaikkien käyttäjien uloskirjaamiseen, joka ei yleensä ole toivottavaa tuotannossa.

**Comment by EssKayz** [comment]
- [ ] Register to the terms and conditions test
- There's a tooltip on the slider that tells you you have to do it to continue :D I'll call that a Feature/Easter egg.
- [x] Equipment class and related things to it's own module
- [x] CSRF has been enabled
- [x] DataRequired added to input fields to stop whitespace inputs
- [x] Added a second whitespace after the classification description, now says " Waterproof " instead of " Waterproof"
- [x] Added a check to stop people from deleting other people's equipment by editing the html form
- [ ] Make classification auto-open after adding a product
- I'll look at this in case I have enough time, sounds like some great spaghetti to implement
- [ ] I'll also look at secret key configuration if I have time, non-issue for now.

Kiitos palautteesta!
(Kommentit englanniksi, koska englanninkielinen layout keyboardilla, ei jaksa-pysty-kykene vaihtaa, ja kun kirjoittaa englanniksi useimmiten, on myös sanojen löytäminen helpompaa  (ctrl-c ctrl-v ä + ö <3 ))
